### ISSUE TITLE
rule automatic teaser is not working?

### ISSUE THREAD

**Issue by stefela** [trinko/contao-zad_sendnews#2]
I tried to apply the rule "teaser" - "automatic teaser" to my send news manager. Maybe I understood it wrong? I thought that it will take the text from the email and cut it to the max length I set. But this is not working. It shows only "..."

**Comment by trinko** [comment]
You are right, "automatic teaser" do exactly what you want, but first you have to assign a value to the Teaser.

Infact, when zad_sendnews scans an email it assigns automatically these fields:
- "headline" from email subject
- "html" from email text in HTML format
- "text" from email plain text 
- "email_subject" from email subject
- "email_sender" from email sender address
  The fields "subheadline'' and "teaser" are initially void, as there is no subheadline or teaser in an email content.

To do an automatic teaser, so you have to:
1) add a rule with target "Teaser", action "replace" and insert in the replace field "{{text}}" or "{{html}}", to replace your void teaser with HTML or plain text
2) add the rule with target "teaser" and action "Automatic teaser" as you already did.

**Comment by stefela** [comment]
Perfect. Now it works. I didn't do the first step in the beginning. I added only the rule "Automatic teaser".
Thanks for the quick help.
