### ISSUE TITLE
image gallery support

### ISSUE THREAD

**Issue by stefela** [trinko/contao-zad_sendnews#3]
I can't send a email with a inline picture from my mobilephone. It is always attached to the email. And I want to use zad_sendnews to post right from my phone to my website. I saw on your to-do-list that you want to add support to Contao Image Gallery content? Will it take long till you have time to add this. It would be perfect if the attached images were not displayed as a filelist but as gallery. This would solve my problem :-)

**Comment by trinko** [comment]
You are lucky.. It is almost done.
It will be released very soon.

**Comment by stefela** [comment]
sounds great!

**Comment by trinko** [comment]
Support to Contao Image gallery added to new version 2.1.0
