### ISSUE TITLE
Image gallery without headline

### ISSUE THREAD

**Issue by stefela** [trinko/contao-zad_sendnews#4]
First, thanks for adding this feature! It works great!
Is it possible to change the headline for the gallery? Or in my case don't display the headline. I tried to do this using the template, but it is insert earlier and not in "galery_default"

**Comment by trinko** [comment]
You can add a new template using this code:

```
<div class="<?php echo $this->class; ?> block"<?php echo $this->cssID; ?><?php if ($this->style): ?> style="<?php echo $this->style; ?>"<?php endif; ?>>

  <?php if ($this->headline): ?>
    <<?php echo $this->hl; ?>><?php echo $this->headline; ?></<?php echo $this->hl; ?>>
  <?php endif; ?>

  <?php echo $this->v2warning; ?>

  <?php echo $this->images; ?>

  <?php echo $this->pagination; ?>

</div>
```

If you don't want the headline drop the lines:

```
  <?php if ($this->headline): ?>
    <<?php echo $this->hl; ?>><?php echo $this->headline; ?></<?php echo $this->hl; ?>>
  <?php endif; ?>
```

**Comment by stefela** [comment]
What is the name of the template that you write the code for? gallery_default?

I found a other solution. I used dcaconfig.php to change the headline:
instead of
$GLOBALS['TL_LANG']['tl_zad_sendnews']['lbl_gallery'] = 'Image Gallery';
I use now
$GLOBALS['TL_LANG']['tl_zad_sendnews']['lbl_gallery'] = '';

Maybe it would be nice to change the headline in the sendnews manager. But for me it is sufficient using DCA.

**Comment by trinko** [comment]
Yes, the template was "gallery_default", but your solution is ok.

Any way, I added to my to-do-list your request.
