### ISSUE TITLE
Teaser Image

### ISSUE THREAD

**Issue by mayfeld** [trinko/contao-zad_sendnews#5]
Hi, do you now any option to use the first image (attached) as a Teaser image and the others as included images in or under the Text.
Thanks.

**Comment by trinko** [comment]
No, sorry. There is no support for teaser image. 
I think I can add it in next release, but I really don't know when...
Anyway, I added it to my to-do list.

**Comment by zirkai** [comment]
Hi, I'm also interested in a teaser-image. Any news to your to-do list?

**Comment by pswerbung** [comment]
Yes, Teaserimage and Teasertext would be GREAT! Still works on Contao 3.5 ;-)
