### ISSUE TITLE
Contao 4 Release/Support

### ISSUE THREAD

**Issue by fkaminski** [trinko/contao-zad_sendnews#7]
Is there plan for Contao 4.x support?

**Comment by hella-schu** [comment]
+1

**Comment by fkaminski** [comment]
Test Version "2.1.0 stable" with Contao 4.4.28:
- Copy files manually to "system/modules/zad_sendnews"
- Clear Cache and use the Install Tool

Problem 1:
Under "Mail Server", the input fields are not reachable/editable with the mouse - 
but by using the tab-keys

Problem 2:
E-Mails with Images as attachments are not autom. connected to the Contao Gallery. A Contao Gallery element will be created but the images are not selected by Default ...

Maybe there is a solution for 2) ?
